package onlinetest;

import java.awt.Color;
import java.awt.Font;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class NewBus extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public NewBus() {
        initComponents();
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        left = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPath = new javax.swing.JTextArea();
        btnAddBus = new javax.swing.JButton();
        btnAddStation = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDistance = new javax.swing.JTextField();
        txtCost = new javax.swing.JTextField();
        txtBusName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtStations = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 1000));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 1000));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left.setBackground(new java.awt.Color(255, 255, 255));
        left.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        left.setForeground(new java.awt.Color(204, 51, 255));
        left.setPreferredSize(new java.awt.Dimension(400, 500));
        left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(51, 255, 255));

        txtPath.setEditable(false);
        txtPath.setBackground(new java.awt.Color(153, 255, 255));
        txtPath.setColumns(5);
        txtPath.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPath.setRows(5);
        txtPath.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtPath);

        left.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 450, 90));

        btnAddBus.setBackground(new java.awt.Color(0, 0, 255));
        btnAddBus.setFont(new java.awt.Font("Siyam Rupali", 1, 18)); // NOI18N
        btnAddBus.setForeground(new java.awt.Color(255, 255, 255));
        btnAddBus.setText("CONFIRM");
        btnAddBus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 153), new java.awt.Color(255, 153, 153)));
        btnAddBus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddBus.setFocusPainted(false);
        btnAddBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBusActionPerformed(evt);
            }
        });
        left.add(btnAddBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 200, 40));

        btnAddStation.setBackground(new java.awt.Color(0, 255, 255));
        btnAddStation.setFont(new java.awt.Font("Siyam Rupali", 1, 18)); // NOI18N
        btnAddStation.setText("ADD NEW STOPPAGE");
        btnAddStation.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255)));
        btnAddStation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddStation.setFocusPainted(false);
        btnAddStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStationActionPerformed(evt);
            }
        });
        left.add(btnAddStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 200, 40));

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel1.setText("Path:");
        left.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 100, 30));

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel2.setText("Bus Name: ");
        left.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 100, 30));

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel3.setText("Cost (/KM): ");
        left.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 120, 30));

        txtDistance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDistanceActionPerformed(evt);
            }
        });
        txtDistance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDistanceKeyTyped(evt);
            }
        });
        left.add(txtDistance, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 280, 50));

        txtCost.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostActionPerformed(evt);
            }
        });
        txtCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCostKeyTyped(evt);
            }
        });
        left.add(txtCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 280, 50));

        txtBusName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtBusName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusNameActionPerformed(evt);
            }
        });
        left.add(txtBusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 280, 50));

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel4.setText("Distance: ");
        left.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 90, 50));

        txtStations.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtStations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStationsActionPerformed(evt);
            }
        });
        left.add(txtStations, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 280, 50));

        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel5.setText("Stations: ");
        left.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 80, 30));

        jPanel1.add(left, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 540, 460));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ADD NEW BUS");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 230, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bus logo1.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 110));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("LOG OUT");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 100, 30));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setFocusPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    int clickUpdate = 1;
    String path="";
    
    private void btnAddBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBusActionPerformed
        if(clickUpdate!=1){
            int res = JOptionPane.showConfirmDialog(this, "Are you sure to add bus record?", "CONFIRM", JOptionPane.YES_NO_OPTION);
            if(res==0){
            try {
                JDBC.insertTable(txtBusName.getText(), String.valueOf(clickUpdate),txtStations.getText(), txtDistance.getText());
                JOptionPane.showMessageDialog(this,"New Bus record has been added to Database");
                adminHome adminHomeFrame = new adminHome();
                adminHomeFrame.setVisible(true);
                adminHomeFrame.pack();
                adminHomeFrame.setLocationRelativeTo(null);
                dispose();
            } catch (Exception e) {
                System.out.println(""+e.getMessage());
            }
            }
            
        }
       else{
             JOptionPane.showMessageDialog(this,"Very less stoppage for this bus!");
        }
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAddBusActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this, "Are you surE?", "CONFIRM", JOptionPane.YES_NO_OPTION);
            if(res==0){
                adminLogin adminloginFrame=new adminLogin();
                adminloginFrame.setVisible(true);
                adminloginFrame.pack();
                adminloginFrame.setLocationRelativeTo(null);
                this.dispose();
            }
         
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void btnAddStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStationActionPerformed
        // TODO add your handling code here:
        if(!txtStations.getText().equals("") && !txtDistance.getText().equals("")
        && !txtBusName.getText().equals("") && !txtCost.getText().equals("")){
            if(clickUpdate==1){
                //create table;
                JDBC.createTable(txtBusName.getText());
                buses.Buses.put(Float.valueOf(txtCost.getText()),txtBusName.getText());
                JDBC.insertBusName( txtBusName.getText(),txtCost.getText());
                txtBusName.setEditable(false);
                txtBusName.setFocusable(false);
                txtCost.setEditable(false);
                txtCost.setFocusable(false);
            }
            //String queryToInsert = "insert into "+txtBusName.getText()+" values ("+clickUpdate+",'"+txtStations.getText()+"',"+txtDistance.getText()+")";
            try{
//                st.execute(queryToInsert);
                JDBC.insertStoppage(txtStations.getText());
                JDBC.insertTable(txtBusName.getText(), String.valueOf(clickUpdate),txtStations.getText(), txtDistance.getText());
                clickUpdate++;
                path += "->"+txtStations.getText();
                txtStations.setText("");
                txtDistance.setText("");
                txtPath.setText(path);
            }catch(Exception e){
                System.out.println("Error while inserting data into database."+e.getMessage());
            }
        }
        else{
             JOptionPane.showMessageDialog(this,"Please fill all of the textfield!");
        }
    }//GEN-LAST:event_btnAddStationActionPerformed

    private void txtDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDistanceActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtDistanceActionPerformed

    private void txtCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostActionPerformed

    private void txtBusNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusNameActionPerformed

    private void txtStationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStationsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        adminHome back=new adminHome();
        back.setVisible(true);
        back.pack();
        back.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtCostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtCostKeyTyped

    private void txtDistanceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDistanceKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtDistanceKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewBus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBus;
    private javax.swing.JButton btnAddStation;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel left;
    public javax.swing.JTextField txtBusName;
    public javax.swing.JTextField txtCost;
    public javax.swing.JTextField txtDistance;
    public static javax.swing.JTextArea txtPath;
    public javax.swing.JTextField txtStations;
    // End of variables declaration//GEN-END:variables
}
